addons:
  coverity_scan:
    branch_pattern: coverity_scan
    build_command: make -C build -j 3
    build_command_prepend: mkdir build; cd build; cmake ..; cd ..
    notification_email: alexey+kvirccoverity@asokolov.org
    project:
      description: Build submitted via Travis CI
      name: kvirc/coverity
dist: trusty
env:
  global:
  - secure: VKCmVzcnJe58/2F5ciPa6FQqnNi/MAUott/rMEFEim9Qk9cFeEuhhhb8JvjoKT1NVC2j+3VJgSczwHtoi06jKUHFqMWJ9pQEa7sNuStSfUGF7ADEjmvooXE/c0nKw5IZf2+pVk3HjvsJerUPOgcSEZSB8JvA7Lb3K1TPEW82xgm7okonE60kz1m0/oDQAAAbocY0uswOPhu5wZ2Df7nseSrLpI56SepHF2r8SJRleeWfMO31inEhexOOqzS5dAE/tTjLjH+nI03JzJA2S3ugkVvU/zs9Ib2xgqWO5JTvk2waOKBnNAaOg9V6S6gYfNt5It0bzeFifzauP6Z7zBuaOJaRKQ+x+dehIv09wgLben2kacJOTI9fjZ7IflYHZH4+rs6eIGcem+C6T64OW0fjkbGnOjSH0wa4uhOacVigNWZik85Ro1JMk6wSDHBmmzjJZ8zmMbBSwd5Za/t8YfffP9y6/250R772tCOeI9Su3Fg+SuWzP3XoaHKbVrKZrrC5mlKnnACgV59E9fQUFJOfVXixGJ09d3hfA48BKoKKXEm9vY4JVSw5gSczJAdLHPGyY37s5nMXuJUY8fVf1bhNJ4iDwWVcQJDF1lJXMFV01pNsSb9xGnyKm+wfOI/HyCQfX3kHHfExrZ2I2he84vV4Sll4Rx1eWluWAbXSSLca4NU=
install:
- export TRAVIS_OS_NAME=linux
- CMAKE_ARGS=""
- "if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then\n    sudo add-apt-repository -y\
  \ ppa:ubuntu-toolchain-r/test # for gcc-7\n    sudo apt-get update\n    sudo apt-get\
  \ install -y libperl-dev libenchant-dev qtmultimedia5-dev libqt5webkit5-dev libqt5svg5-dev\
  \ libqt5x11extras5-dev libphonon4qt5-dev libphonon4qt5experimental-dev gcc-7 g++-7\n\
  \    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90\n   \
  \ sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90\n\n    if\
  \ [ -z \"$DEBUILD\" ]\n    then\n      CMAKE_ARGS=\"$CMAKE_ARGS -DWANT_KDE=$WANT_KDE\"\
  \n      if [[ \"$WANT_KDE\" == \"YES\" ]]; then\n        sudo apt-get install -y\
  \ kdelibs5-dev\n      fi\n    else\n      sudo apt-get install -y devscripts debhelper\
  \ zlib1g-dev libx11-dev libxrender-dev libssl-dev qttools5-dev-tools qttools5-dev\
  \ pkg-config libxss-dev python-dev dput gnupg libdistro-info-perl fakeroot\n   \
  \ fi\nfi\n"
- "if [[ \"$TRAVIS_OS_NAME\" == \"osx\" ]]; then\n  brew update\n  brew install qt5\
  \ enchant openssl\n  # want cmake newer than by default in travis osx\n  brew upgrade\
  \ cmake\n  CMAKE_ARGS=\"$CMAKE_ARGS -DOPENSSL_ROOT_DIR=$(brew --prefix openssl)\"\
  \n  export CMAKE_FRAMEWORK_PATH=\"$CMAKE_FRAMEWORK_PATH:$(brew --prefix qt5)\"\n\
  fi\n"
language: cpp
script:
- /bin/true
sudo: required

